### PR TITLE
Separate compilation

### PR DESCRIPTION
**Pull request by lichtemo**
I hope that I merged all changes in the master branch to the repository.
This branch is able to bootstrap by its own with a baseline using the global compiler.

### CODE REVIEW

**Comment by Gohla** [comment]
Did you merge with master or java-bootstrap? The master branch is the old C-bootstrapped compiler, don't merge that!

**Comment by lichtemo** [comment]
Sorry, it is java-bootstrap.
I  hope that you can build the branch. On the buildfarm its working. You do not need a submodule with another branch of my fork anymore. I created an additional pull request for a fork of java-front, which adapts the build scrips for separate-compilation).

From my experiences with bootstrapping I expect the integration tests to fail :). Either because of build script problems, problems because the generated Java files changes or by wrong module names or missing imports.

I detected another problem with Overlays, which uses constructors from libraries (libstratego-xxx). We can discuss that on Thursday. I will not be reachable tomorrow, but at Wednesday I am again.

Moritz

**Comment by Gohla** [comment]
Okay, but we cannot automatically merge this because there are conflicts with the current java-bootstrap branch. Can you merge the latest java-bootstrap into your branch?

**Comment by Gohla** [comment]
Thanks :+1:

**Comment by lichtemo** [comment]
Should I continue to work on my forks or on the branches in the metaborg repo?

**Comment by Gohla** [comment]
Working with the metaborg repos might be best, because they will trigger integration builds on our build farm.

**Pull request merged**
