### PR TITLE
Feature: Pattern-matched term parameters

### PR DESCRIPTION
**Pull request by Virtlink**
Term parameters in strategies and rules can now do pattern matching.The syntax is as follows:

> You can specify any term as a term parameter to a strategy or rule, not just variables. You can mix-and-match term variables with term patterns:
> 
>      mystrategy(|"exact", v) = !v
>
> Use a wildcard if you don't care about the value:
>
>      mystrategy(|_) = !()
>
> The syntax works for both rules and strategies:
>
>      myrule(|"exact"): x -> x
>
> Strategy application is supported:
>
>      mystrategy(|<newname> "a") = !()
>
> ...also without a term:
>
>      myrule(|<id>): _ -> ()
>

As an example, a switch-case using strategies:

	to-english(|1) = !"one"
	to-english(|2) = !"two"
	to-english(|_) = !"many"

This features was proposed by Daco Harkes and implemented by Daco Harkes and Daniël Pelsmaeker. See [StrategoXT#907](http://yellowgrass.org/issue/StrategoXT/907) for more information.

### CODE REVIEW

**Comment by Gohla** [comment]
I assume you did but just making sure, did you bootstrap StrategoXT and ran all the tests? 
Also, I don't see any new tests for this feature, could you please add some tests for regression testing?

**Comment by Virtlink** [comment]
Yes, I ran the bootstrap and all tests. Will add some tests for this feature.

**Comment by Virtlink** [comment]
Added tests and tested them by running the bootstrap with all tests.

**Comment by Gohla** [comment]
Great! Looks good to me, @vvergu @eelcovisser any comments or can it be merged?

**Comment by vvergu** [comment]
This looks good, i'll merge it once Stratego/XT is built and bootstrapped on Jenkins. @Gohla what's the outlook for that?

**Comment by Gohla** [comment]
It is built as part of the Spoofax build, do you want a separate build as well?

**Comment by vvergu** [comment]
I see. Yes, that would be nice. And which branch is built?

**Comment by Gohla** [comment]
java-bootstrap, which the Maven build stuff was merged into

**Comment by vvergu** [comment]
Ok. Thanks @Virtlink and @Gohla. I'll merge this.

**Pull request merged**
